### ISSUE TITLE
the number of CIs in the toolbar is not correct.

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/ITSMConfigurationManagement#10]
the number of CIs in the toolbar is not correct.
the number always refers to all

![image](https://github.com/RotherOSS/ITSMConfigurationManagement/assets/80096822/d583fedb-d15d-4148-a6a9-3860078e0d09)

![image](https://github.com/RotherOSS/ITSMConfigurationManagement/assets/80096822/aafa249c-aee5-4d4b-9b25-d147658ca7fb)

**Comment by stefanhaerter** [comment]
Should be fixed with commit 7d261e3d8afdd01c5f6eb3041cf9251fb4ebbcf6.
Leaving this open until further confirmation.
