### ISSUE TITLE
ITSM::ConfigItem::Class::Category not created after the Import

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/ITSMConfigurationManagement#11]
ITSM::ConfigItem::Class::Category not created after the Import

![image](https://github.com/RotherOSS/ITSMConfigurationManagement/assets/80096822/544e341a-b1c5-483d-b38e-444b930423d5)

![image](https://github.com/RotherOSS/ITSMConfigurationManagement/assets/80096822/987b580f-7f5f-4c25-8a3f-de066a31caf0)

**Comment by stefanhaerter** [comment]
Confirmed. Bug should be fixed with commit 0665d57467c7acf39fc729542bdcefb421bd3c16. Leaving this open until further confirmation :)
