### ISSUE TITLE
Sorting the classes is not understandable

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/ITSMConfigurationManagement#12]
Sorting the classes is not understandable.
In the configuration of categories, looks like it works.

![image](https://github.com/RotherOSS/ITSMConfigurationManagement/assets/80096822/800170d5-e8a8-4b97-903d-7d2a8e975d01)

![image](https://github.com/RotherOSS/ITSMConfigurationManagement/assets/80096822/b24679b4-2520-4a03-ba6a-5954d205f4c8)

**Comment by stefanhaerter** [comment]
Hi Olli,

I couldn't reproduce this:

![Bildschirmfoto vom 2024-06-14 08-44-53](https://github.com/RotherOSS/ITSMConfigurationManagement/assets/46650328/1f59157a-472e-4506-8290-6a96bffdff9a)

The sorting is based on the names defined in the GeneralCatalog category elements, but from your second screenshot I would assume that there is no translation in place which could mess up the order.

Can you provide any more information about how you configured the system that could help to reproduce the bug?

Kind regards,
Stefan
