### ISSUE TITLE
No possibility to add name or other default fields in AgentITSMConfigItemSearch

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/ITSMConfigurationManagement#13]
No possibility to add name or other default fields in AgentITSMConfigItemSearch (i.e. in the results). 

And Please enable per default:
ITSMConfigItem::Frontend::AgentITSMConfigItemSearch###Defaults###Name and ITSMConfigItem::Frontend::AgentITSMConfigItemSearch###Defaults###Number

**Comment by stefanhaerter** [comment]
Done. Also fixed AgentITSMConfigItemSearch not respecting the default values set.
