### ISSUE TITLE
CMDB Search network problem after changing class

### ISSUE THREAD

**Issue by fabbaum** [RotherOSS/ITSMConfigurationManagement#16]
When I change the class in the CMDB search of OTOBO 11.0.5, OTOBO detects a network problem. 
<img width="643" alt="image" src="https://github.com/user-attachments/assets/99294bef-a028-4163-ae47-34f63f32093e">
<img width="467" alt="image" src="https://github.com/user-attachments/assets/63e95147-5ccb-48ed-b43f-96dbf9e5fb99">

**Comment by stefanhaerter** [comment]
I just pushed a commit which should fix the issues. So expecting this to be fixed with the next package release.
