### ISSUE TITLE
ConfigItemGet() does not allow to turn off caching

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/ITSMConfigurationManagement#2]
According to the POD of ConfigItemGet() the parameter Cache can be used for turning off cacheíng.

https://github.com/RotherOSS/ITSMConfigurationManagement/blob/d6892c4c0c9c02fe93d70d980f9650d64ac93d8b/Kernel/System/ITSMConfigItem.pm#L218-L226

But the implementation does not reflect this.

**Comment by stefanhaerter** [comment]
The commit seemingly does not have anything to do with this issue.

**Comment by stefanhaerter** [comment]
The parameter has been removed from the POD in commit 1b159a863954431f04e579d980e7f37eb325f348. Closing the issue.
