### ISSUE TITLE
DynamicField CustomerUser is treated as a mandatory field

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/ITSMConfigurationManagement#20]
The DynamicField CustomerUser is treated as a mandatory field, even if it is not configured as a mandatory field. In the example, it is configured as ‘Multivalue’ and ‘Autocomplete’.

Possibly also in the standard (ticket, etc.) but detected here.

**Comment by stefanhaerter** [comment]
I tried to reproduce this, but was not sucessful. I think this could have been fixed with https://github.com/RotherOSS/otobo/issues/3730.
I suggest to close the issue.

**Comment by stefanhaerter** [comment]
Closing the issue as solved.
