### ISSUE TITLE
CI deletion fails when internally ("CI") linked to other CIs.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/ITSMConfigurationManagement#23]
The link table uses foreign keys and has to be cleaned in advance.

**Comment by stefanhaerter** [comment]
This does not only affect the link table, but also dynamic field values. For example, if I create a config item which is linked to another config item via a dynamic field reference, cleaning the link table won't be sufficient.

**Comment by stefanhaerter** [comment]
Commits are pushed to OPMS, closing the issue.
