### ISSUE TITLE
Importing CIs with referencing fields is difficult

### ISSUE THREAD

**Issue by ybeckmann21** [RotherOSS/ITSMConfigurationManagement#27]
I try to import CIs from another CMDB via CSV but its difficult to do so because of the Structure of the import.

Example:
I want to import CIs of the class "Virtual Servers". They have the attribute "Operating System" which references the class "Operating System". 
So I import the Operating Systems first and try to map the Virtual Servers on the OS in the import afterwards. 
The Problem is, that the Key DynamicField_ITSM-ReferenceToOS expects the ConfigItemID of every OS. As far as I see, there is no easy way to get the ConfigItemID of multiple CIs right now. The Export only delivers the Number, Name etc.
The only way is to run a SQL Query which matches the Names and IDs. 

Would it be possible to make the ConfigItemID easier accessible or is there another way to import CIs with references?
Thanks for your help.
Yannic

**Comment by StefanRother-OTOBO** [comment]
Hi Yannic,

Yes, in the next version we add a new option to our reference fields in Admin -> DynamicFields called "External-source key". Here you are able to choose another field for Webservice or Import/Export References.

We publish the new version in the next days, if you have trouble to use the new option, please reopen this issue.

Best wishes,

Stefan
