### ISSUE TITLE
Displaying Customer specific CIs in the Customer Portal 

### ISSUE THREAD

**Issue by ybeckmann21** [RotherOSS/ITSMConfigurationManagement#30]
So far we could only manage to make a full CI Category available in the Customer Portal, is there a way to only display the CIs of the own Company to the User?

**Comment by ybeckmann21** [comment]
I found out how to handle it with the permission conditions

**Comment by StefanRother-OTOBO** [comment]
Hi,

We have released a new CMDB version 11 today, which finally includes useful documentation. 
However, we are still working hard on the topic documentation.

Best wishes 

Stefan Rother
Team OTOBO
