### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/ITSMConfigurationManagement#4]
I run OTOBO 11 with Apache2 and MariaDB. When installing the ITSMConfigurationManagement package (and previously installed GeneralCatalog and ITSMCore, seemingly makes no difference if fresh or 'polluted' system), the package is installed, but I get stuck at the penultimate package installation screen and a file 'index.pl' is downloaded. I attach an example for debugging (with the .txt postifx because GitHub won't allow it otherwise).

[index.pl.txt](https://github.com/RotherOSS/ITSMConfigurationManagement/files/13948552/index.pl.txt)

When installing the package via console, I see the output of the upgrade script, which is also included into the index.pl file at the beginning, so I assume that it is a matter of wrongly directed output.

**Comment by bschmalhofer** [comment]
@stefanhaerter   Does this problem still persist?

**Comment by stefanhaerter** [comment]
When I tested the last time, it did - which was approximately some time last week.

**Comment by stefanhaerter** [comment]
Installation bug is gone in the meantime by removing the execution of a console command from var/packagesetup.
