### ISSUE TITLE
Loop over hash

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/ITSMConfigurationManagement#5]
In _Kernel/GenericInterface/Operation/ConfigItem/ConfigItemSearch.pm_ there is some fishy code:

```
                    # assamble the final value from the parts
                    for my $NewKey ( %{$NewXMLDataPart} ) {
                        for my $Item ( @{ $NewXMLDataPart->{$NewKey} } ) {
                            push @{ $NewXMLData->{$NewKey} }, $Item;
                        }
                    }
```

The loop is over keys and values of `%{$NewXMLDataPart}` but should propably be only over the keys. This was found with the helpl of  [Perl::Critic::Policy::Variables::ProhibitLoopOnHash](https://metacpan.org/pod/Perl::Critic::Policy::Variables::ProhibitLoopOnHash).

**Comment by stefanhaerter** [comment]
I suggest to close this issue. The code in question was removed with a rework of the module.

**Comment by bschmalhofer** [comment]
Closing this issue, see the comment of @stefanhaerter .
