### ISSUE TITLE
CIs from the Software & Operating Systems class cannot be created

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/ITSMConfigurationManagement#6]
CIs from the Software & Operating Systems class cannot be created (even if licenses have been created)

The date fields or lens (period from/until) from the liceense does not work correctly.

![image](https://github.com/RotherOSS/ITSMConfigurationManagement/assets/80096822/7287c3e0-1778-44b0-a41b-f8e28487b654)

![image](https://github.com/RotherOSS/ITSMConfigurationManagement/assets/80096822/95af2fa5-218a-420e-854e-4299eef5cab2)

**Comment by stefanhaerter** [comment]
Solved with merging https://github.com/RotherOSS/otobo/pull/3511
