### ISSUE TITLE
Name of the DynamicFiled ITSMIPNetwork-IPRanchStart

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/ITSMConfigurationManagement#7]
shouldn't it be called better

- ITSMIPNetwork-IPRangeStart
- ITSMIPNetwork-IPRangeEnd

**Comment by StefanRother-OTOBO** [comment]
Hi Olli, 

isn't that exactly what the fields are called? 
But anyway, the fields and labels can of course be customised.

Thanks,
Stefan
