### ISSUE TITLE
Lens data of the CI class license not correct

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/ITSMConfigurationManagement#9]
the Lens data of the CI class license not correct.

- the license type will not be shown

![image](https://github.com/RotherOSS/ITSMConfigurationManagement/assets/80096822/fcdb9dd1-8bf1-4dec-a5ce-6b971c472968)

- and when i remove the license, the license count is always shown

![image](https://github.com/RotherOSS/ITSMConfigurationManagement/assets/80096822/24a0649a-3419-4296-9310-a5de6aafec96)

**Comment by stefanhaerter** [comment]
Solved with merging https://github.com/RotherOSS/otobo/pull/3511
